In [2]:
import numpy as np 

In [6]:
x,y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-2,2,5))

In [4]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [10]:
z = x**2 + y**2
z

array([[5.  , 4.25, 4.  , 4.25, 5.  ],
       [2.  , 1.25, 1.  , 1.25, 2.  ],
       [1.  , 0.25, 0.  , 0.25, 1.  ],
       [2.  , 1.25, 1.  , 1.25, 2.  ],
       [5.  , 4.25, 4.  , 4.25, 5.  ]])

In [8]:
x

array([[-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ]])